create extension if not exists pgcrypto;

create table if not exists public.tool_leads (
  id uuid primary key default gen_random_uuid(),
  tool text not null check (
    tool in (
      'intake-deadline-planner',
      'occupation-in-demand',
      'compare-countries',
      'express-entry-tracker'
    )
  ),
  inputs jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  email text,
  whatsapp_clicked boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists tool_leads_created_at_idx
  on public.tool_leads (created_at desc);

create index if not exists tool_leads_tool_idx
  on public.tool_leads (tool);

alter table public.tool_leads enable row level security;

comment on table public.tool_leads is
  'Lead submissions generated by Idol Immigration Momentum Tools. Writes use the server-side service role.';
